-
  hosts: target2
  name: "deploy website from ansible"
  tasks:
    - name: "install extra"
      yum:
        name:
          - epel-release
          - python-pip
          - python-devel
          - mysql-devel
          - gcc
          - MySQL-python

    - name: "install firewalld"
      yum: "name=firewalld state=present"

    - name: "reload service firewalld"
      systemd: "name=firewalld state=reloaded"

    - name: "start service firewalld, if not started"
      service: "name=firewalld state=started"

    - name: "enable service firewalld"
      service:
        enabled: "yes"
        name: firewalld

    - name: "install mariadb-server"
      yum: "name=mariadb-server state=present"

    - name: "start service  mariadb, if not started"
      service: "name=mariadb state=started"

    - name: "enable service Mariadb"
      service: "name=mariadb enabled=yes"

    - firewalld: "port=3306/tcp permanent=yes state=enabled"
      name: "permit traffic for sql service"

    - name: "reload service firewalld"
      systemd: "name=firewalld state=reloaded"

    -  name: "Create a new database with name 'ecomdb'"
       mysql_db:
        name: ecomdb
        state: present

    - name: "Create database user with name 'ecomuser' and password 'ecompassword' with all database privileges"
      mysql_user: "name=ecomuser  password=ecompassword  priv=*.*:ALL state=present check_implicit_admin=yes"

    - name: "Creating a file with content"
      copy:
        content: |
            USE ecomdb; CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
            INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");
        dest: "db-load-script.sql"

    - name: "upload db-load-script.sql"
      ignore_errors: yes
      mysql_db:
        name: ecomdb
        state: import
        target: db-load-script.sql


    - name: "permit traffic for http"
      firewalld: "port=80/tcp permanent=yes state=enabled"

    - name: "reload service firewalld"
      systemd: "name=firewalld state=reloaded"

    - name: "install httpd"
      yum:
        name: httpd

    - name: "install php"
      yum:
        name:
          - php
          - php-mysql

    - name: "Change DirectoryIndex index.html to DirectoryIndex index.php to make the php page the default page"
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "DirectoryIndex index.html"
        replace: "DirectoryIndex index.php"

    - name: "start service httpd, if not started"
      service: "name=httpd state=started"
    - name: "enable service firewalld"
      service:
        enabled: "yes"
        name: firewalld
        
    - name: "install git"
      yum: "name=git state=present"
    -
      git:
        dest: /var/www/html/
        force: true
        repo: "https://github.com/kodekloudhub/learning-app-ecommerce.git"
      name: "Clone repository to /var/www/html/"

    - name: "Change DirectoryIndex index.html to DirectoryIndex index.php to make the php page the default page"
      replace:
        path: /var/www/html/index.php
        regexp: "172.20.1.101"
        replace: localhost
